### ISSUE TITLE
TypeError after pydantic update

### ISSUE THREAD

**Issue by filippotp** [fattureincloud/fattureincloud-python-sdk#60]
I am using this package within a Django application. Python version is 3.11.4. 
After updating pydantic package from version 1.10.9 to 2.0.2, I get an exception during application launch by command `python manage.py runserver 8000`:

```
C:\<path-to-project>\venv\lib\site-packages\pydantic\_internal\_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
WARNING:root:No DATABASE_URL environment variable set, and so no databases setup
C:\Users\filip\Documents\PyCharm\delego\venv\lib\site-packages\pydantic\_internal\_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
Watching for file changes with StatReloader
INFO:django.utils.autoreload:Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\<path-to-project>\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\<path-to-project>\venv\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "C:\<path-to-project>\venv\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\<path-to-project>\venv\lib\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "C:\<path-to-project>\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\<path-to-project>\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\<path-to-project>\venv\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\<path-to-project>\venv\lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\<path-to-project>\events\models.py", line 35, in <module>
    from utility.invoicing import InvoicingManager
  File "C:\<path-to-project>\utility\invoicing.py", line 5, in <module>
    import fattureincloud_python_sdk as sdk
  File "C:\<path-to-project>\venv\lib\site-packages\fattureincloud_python_sdk\__init__.py", line 21, in <module>
    from fattureincloud_python_sdk.api.archive_api import ArchiveApi
  File "C:\<path-to-project>\venv\lib\site-packages\fattureincloud_python_sdk\api\__init__.py", line 4, in <module>
    from fattureincloud_python_sdk.api.archive_api import ArchiveApi
  File "C:\<path-to-project>\venv\lib\site-packages\fattureincloud_python_sdk\api\archive_api.py", line 25, in <module>
    from fattureincloud_python_sdk.models.create_archive_document_request import (
  File "C:\<path-to-project>\venv\lib\site-packages\fattureincloud_python_sdk\models\__init__.py", line 27, in <module>
    from fattureincloud_python_sdk.models.client import Client
  File "C:\<path-to-project>\venv\lib\site-packages\fattureincloud_python_sdk\models\client.py", line 26, in <module>
    from fattureincloud_python_sdk.models.payment_method import PaymentMethod
  File "C:\<path-to-project>\venv\lib\site-packages\fattureincloud_python_sdk\models\payment_method.py", line 30, in <module>
    class PaymentMethod(BaseModel):
  File "C:\<path-to-project>\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "C:\<path-to-project>\venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "C:\<path-to-project>\venv\lib\site-packages\pydantic\_internal\_fields.py", line 97, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "C:\<path-to-project>\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "C:\<path-to-project>\venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 224, in eval_type_lenient
    return typing._eval_type(value, globalns, localns)  # type: ignore
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\typing.py", line 326, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\typing.py", line 691, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: conlist() got an unexpected keyword argument 'max_items'
```

**Comment by valmoz** [comment]
Hi @filippotp 
currently only version 1 of Pydantic is supported. Since version 2 of the library was released [just recently](https://docs.pydantic.dev/latest/changelog/), we should update the requirements file accordingly.

We don't know when we'll be able to switch to the v2 of the library, since we depend on the OpenAPI generator to release a new version of the SDK.

Thanks
Mauro

**Comment by emajo** [comment]
Hi @filippotp, we resolved this problem in the [latest release](https://pypi.org/project/fattureincloud-python-sdk/) (2.0.15), thanks for the pr, we edited the templates for the generation of our python sdk to fix this issue so I'm going to close your PR.

Thanks again,
Emanuele.
